config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path

from .views import index, page_create, page_update, page_delete, page_detail, page_search, about, index_filter

app_name = "pages"
urlpatterns = [
    path("", index, name="index"),
    path("filter/<slug:tag>/", index_filter, name="filter"),
    path("create/", page_create, name="create"),
    path("update/<int:pk>/", page_update, name="update"),
    path("delete/<int:pk>/", page_delete, name="delete"),
    path("detail/<int:pk>/", page_detail, name="detail"),
    path("search/", page_search, name="search"),
    path("about/", about, name="about"),
]

pages/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
from taggit.managers import TaggableManager

class Page(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    def __str__(self):
        return self.title

        

pages/forms.py
from django import forms
from .models import Page

class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ["title", "content", "tags"]
        labels = {
            "title": "Title",
            "content": "Content",
            "tags": "Tags",
        }
        help_texts = {
            "title": "Enter the title of the page",
            "content": "Enter the content of the page",
            "tags": "Enter tags for the page",
        }
        error_messages = {
            "title": {
                "max_length": "This title is too long.",
            },
        }
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control"}),
            "tags": forms.TextInput(attrs={"class": "form-control"}),
        }

pages/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from .forms import PageForm
from .models import Page
from taggit.models import Tag

def index(request):
    pages = Page.objects.all()
    tags = Tag.objects.all()
    context = {
        "pages": pages,
        "tags": tags,
    }
    return render(request, "pages/index.html", context)

def index_filter(request, tag):
    pages = Page.objects.filter(tags__name=tag)
    tags = Tag.objects.all()
    context = {
        "pages": pages,
        "tags": tags,
    }
    return render(request, "pages/index.html", context) 

def page_create(request):
    form = PageForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = PageForm()
        return redirect("pages:index")
    context = {
        "form": form
    }
    return render(request, "pages/page_create.html", context)

def page_update(request, pk):
    page = Page.objects.get(pk=pk)
    form = PageForm(request.POST or None, instance=page)
    if form.is_valid():
        form.save()
    context = {
        "form": form
    }
    return render(request, "pages/page_update.html", context)

def page_delete(request, pk):
    page = Page.objects.get(pk=pk)
    page.delete()
    return render(request, "pages/page_delete.html")

def page_detail(request, pk):
    page = Page.objects.get(pk=pk)
    context = {
        "page": page
    }
    return render(request, "pages/page_detail.html", context)   

def page_search(request):
    if request.method == POST:
        if request.POST['search']:
            search = request.POST['search']
            pages = Page.objects.filter(title__icontains=search)
            return render(request, "pages/home.html", {"pages": pages})
    else:
        return render(request, "pages/home.html")

    return render(request, "pages/home.html")

    
def home(request):
    pages = Page.objects.all()
    context = {
        "pages": pages,
    }
    return render(request, "pages/home.html", context)
   


def about(request):
    return render(request, "pages/about.html")

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django + Tailwind CSS + Flowbite</title>

  {% compress css %}
  <link rel="stylesheet" href="{% static 'src/output.css' %}">
  {% endcompress %}

</head>

<body class="bg-green-50">

  <!-- Add this -->
  <nav class="bg-green-50 border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
    <div class="container flex flex-wrap items-center justify-between mx-auto">
      <a href="{{ .Site.Params.homepage }}/" class="flex items-center">
        <img src="{% static 'images/logo.png' %}" class="h-6 mr-3 sm:h-9" alt="Flowbite Logo" />
        <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Flowbite Django</span>
      </a>
      <button data-collapse-toggle="mobile-menu" type="button"
        class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
        aria-controls="mobile-menu" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
            clip-rule="evenodd"></path>
        </svg>
        <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
            clip-rule="evenodd"></path>
        </svg>
      </button>
      <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
        <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
          <li>
            <a href="#"
              class="block py-2 pl-3 pr-4 text-white bg-green-700 rounded md:bg-transparent md:text-green-700 md:p-0 dark:text-white"
              aria-current="page">Home</a>
          </li>
          <li>
            <a href="#"
              class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
          </li>
          <li>
            <a href="#"
              class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Services</a>
          </li>
          <li>
            <a href="#"
              class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Pricing</a>
          </li>
          <li>
            <a href="#"
              class="block py-2 pl-3 pr-4 text-gray-700 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End of new HTML -->

  <div class="container mx-auto mt-4">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
</body>

</html>

templates/accounts/new_doctor.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Sign up{% endblock %}

{% block content %}


<style>
  .form-signup {
    width: 100%;
    max-width: 800px;
    padding: 15px;
    margin: auto;
    margin-top: 3rem;
  }
</style>

<div class="container">
  <div class="row">
    <main class="form-signup">
      <form method="post" class="form">
        <h1 class="h3 mb-3 fw-normal">New Doctor Sign up</h1>
        {% csrf_token %}

        {{ user_form|crispy }}
        <button class="btn btn-success" type="submit">Sign up</button>
      </form>

    </main>


  </div>
</div>

{% endblock content %}

templates/accounts/new_patient.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Sign up{% endblock %}

{% block content %}


<style>
  .form-signup {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
    margin-top: 3rem;
  }
</style>

<div class="container">
  <div class="row">
    <main class="form-signup">
      <form method="post" class="form">
        <h1 class="h3 mb-3 fw-normal">New Patient Sign up</h1>
        {% csrf_token %}

        {{ user_form|crispy }}
        <button class="btn btn-success" type="submit">Sign up</button>
      </form>

    </main>


  </div>
</div>

{% endblock content %}

templates/accounts/user_profile.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Sign up{% endblock %}

{% block content %}


<style>
    .form-signup {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
        margin-top: 3rem;
    }
</style>

<div class="container">
    <div class="row">
        <main class="form-signup">
            <form method="post" class="form">
                <h1 class="h3 mb-3 fw-normal">Profile update</h1>
                {% csrf_token %}

                {{ profile_form|crispy }}
                <button class="btn btn-success" type="submit">Profile Save</button>
            </form>

        </main>


    </div>
</div>

{% endblock content %}

templates/accounts/user_update.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Sign up{% endblock %}

{% block content %}


<style>
    .form-signup {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
        margin-top: 3rem;
    }
</style>

<div class="container">
    <div class="row">
        <main class="form-signup">
            <form method="post" class="form">
                <h1 class="h3 mb-3 fw-normal">User update</h1>
                {% csrf_token %}

                {{ user_form|crispy }}
                <button class="btn btn-success" type="submit">Update</button>
            </form>

        </main>


    </div>
</div>

{% endblock content %}

templates/icases/icase_create.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>Case Creation</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock content %}

templates/icases/icase_detail.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}

<h1>Case Detail</h1>
<a href="{% url 'dashboard:icase-list' %}">Create a new case</a>
<h1>{{ icase.name }}</h1>
<p>{{ icase.id }}</p>
<p>{{ icase.category }}</p>
<p>{{ icase.target_cost }}</p>
<p>{{ icase.description }}</p>
<p>{{ icase.report }}</p>
<p>{{ icase.tag }}</p>
<p>Created At: {{ icase.created_at }}</p>

<h2>Comments</h2>
{% for comment in icase_comments %}
<p>{{ comment.user }}</p>
<p> {{ comment.cost }}</p>
<p> {{ comment.terms }}</p>
{% endfor %}

{% endblock content %}

templates/icases/icase_list.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>Case list</h1>
<a href="{% url 'dashboard:icase-create' %}">Create a new case</a>
<a href="{% url 'dashboard:icase-list' %}">List</a>

{% for icase in icases %}
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ icase.name }}</h5>
        <p class="card-text">{{ icase.description }}</p>
        <p class="card-text"><small class="text-muted">{{ icase.created_at }}</small></p>
        <a href="{{ icase.get_absolute_url }}">{{ icase.id }}</a>
    </div>
</div>
{% endfor %}

{% endblock content %}

templates/pages/about.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/pages/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}

{% for page in pages %}

<article class="mx-auto w-full max-w-2xl format format-sm sm:format-base lg:format-lg format-blue dark:format-invert">
  <header class="mb-4 lg:mb-6 not-format">
    <address class="flex items-center mb-6 not-italic">
      <div class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white">
        <img class="mr-4 w-16 h-16 rounded-full" src="https://flowbite.com/docs/images/people/profile-picture-2.jpg"
          alt="Jese Leos">
        <div>
          <a href="#" rel="author" class="text-xl font-bold text-gray-900 dark:text-white">Jese Leos</a>
          <p class="text-base text-gray-500 dark:text-gray-400">Graphic Designer, educator & CEO Flowbite</p>
          <p class="text-base text-gray-500 dark:text-gray-400"><time>{{ page.date|date:"F j, Y" }}</time></p>
        </div>
      </div>
    </address>
    <h1 class="mb-4 text-3xl font-extrabold leading-tight text-gray-900 lg:mb-6 lg:text-4xl dark:text-white">
      {{ page.title}}
    </h1>
  </header>
  <p class="lead">
    {{ page.content}}
  </p>
  <p>
    {{ page.tag}}
  </p>
</article>
<hr>







{% endfor %}


{% endblock content %}

templates/pages/index.html
{% extends "_base.html" %}

{% block content %}
<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
        <div class="mx-auto max-w-screen-sm text-start lg:mb-16 mb-8">
            <h2 class="mb-4 text-3xl lg:text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">
                Our Blog
            </h2>
            <p class="font-light text-gray-500 sm:text-xl dark:text-gray-400">
                {% for tag in tags %}

                <a href="{% url 'pages:filter' tag %}"
                    class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-cyan-200 dark:focus:ring-cyan-800">
                    <span
                        class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                        {{ tag }}
                    </span>
                </a>
                {% endfor %}
                <a href="{% url 'pages:index' %}"
                    class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-cyan-200 dark:focus:ring-cyan-800">
                    <span
                        class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                        ALL
                    </span>
                </a>
            </p>
            <p class="font-light text-gray-500 sm:text-xl dark:text-gray-400">
                <a href="{% url 'pages:create' %}" class="text-primary-500 hover:underline dark:text-primary-400">Create
                    a new page</a>
            </p>
        </div>
        <div class="grid gap-8 lg:grid-cols-1">
            {% for page in pages %}
            <article
                class="p-6 bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
                <div class="flex justify-between items-center mb-5 text-gray-500">
                    <span
                        class="bg-primary-100 text-primary-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded dark:bg-primary-200 dark:text-primary-800">
                        <svg class="mr-1 w-3 h-3" fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zM14.553 7.106A1 1 0 0014 8v4a1 1 0 00.553.894l2 1A1 1 0 0018 13V7a1 1 0 00-1.447-.894l-2 1z">
                            </path>
                        </svg>
                        Tutorial
                    </span>
                    <span class="text-sm">14 days ago</span>
                </div>
                <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                    <a href="#">
                        {{ page.title }}
                    </a>
                </h2>
                <p class="mb-5 font-light text-gray-500 dark:text-gray-400">
                    {{ page.content }}
                </p>
                <div class="flex justify-between items-center">
                    <div class="flex items-center space-x-4">
                        <p>
                            {% for tag in page.tags.all %}
                            <span
                                class="bg-blue-100 text-blue-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300">
                                {{ tag }}
                            </span>

                            {% endfor %}
                        </p>

                    </div>

                </div>
            </article>
            {% endfor %}
        </div>
    </div>
</section>


{% endblock content %}

templates/pages/page_create.html
{% extends "_base.html" %}

{% block content %}
<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
        <div class="mx-auto max-w-screen-sm text-start lg:mb-16 mb-8">
            <h2 class="mb-4 text-3xl lg:text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">
                Our Blog
            </h2>
            <p class="font-light text-gray-500 sm:text-xl dark:text-gray-400">
                Create a new page
            </p>
        </div>
        <div class="grid gap-8 lg:grid-cols-1">
            <div class="p-6 bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
            </div>
        </div>
</section>


{% endblock content %}